### ISSUE TITLE
Some issues about 4.5 Retraining Experiments with VastTrack.

### ISSUE THREAD

**Issue by ElliottZhen** [HengLan/VastTrack#10]
Hello~
Great work, I have a few questions:
In your paper 4.5 Retraining Experiments with VastTrack, did you train with VastTrack only after OSTrack had been trained for 300 rounds on the original 4 datasets? If so, what is your specific training configuration, such as the number of rounds, the number of samples per round, etc.
Have you tried to train COCO, TrackingNet, LaSOT, Got-10k, and VastTrack together in geometric proportion?
Thank you
@HengLan

**Comment by HengLan** [comment]
Hello,

Sorry for the late reply. 

Thanks for your interest in our work. In this retraining experiment, the training configuration is similar to that in OSTrack, and yes, we simply fine-tune the OSTrack using data from VastTrack for another 100 epochs. Other parameters are kept the same.

For your another question, we have not yet conducted experiments using all datasets together, as the preparation for such an experiment would take too much time (since you have much more data, you will want to increase the training time by increasing the number of epochs), while our primary focus  in this work has been on data collection, labeling, and refining the annotations. In the future, we may try this and we believe other researchers in the tracking community may also train their models using all these available datasets. We can look forward to that. 

Thanks.
