### ISSUE TITLE
Questions in Table 1

### ISSUE THREAD

**Issue by jimmy-dq** [HengLan/VastTrack#5]
Hi all, thanks for your great work. 
I am wondering that is the notation correct in table 1? since the original droptrack does not use the temporal information for tracking.  Do you modify the original code to add the temporal information?

**Comment by HengLan** [comment]
> Hi all, thanks for your great work. I am wondering that is the notation correct in table 1? since the original droptrack does not use the temporal information for tracking. Do you modify the original code to add the temporal information?

Hi jimmy-dq

Thank you very much for your comment. The notation for DropMAE should be DropTrack (DropMAE is the backbone, and we will correct this typo). In our evaluation, we don't modify the code of DropTrack. The reason why we add the 'temporal check' for DropTrack is because temporal relationship in the video has been explored and effectively utilized during pre-training of DropMAE which is the foundation of DropTrack (, and thus we think temporal information has been explored for tracking algorithms that are developed based DropMAE). But of course, we agree that original DropTrack itself does not explicitly exploit the temporal information. We may make appropriate changes or explanations for DropTrack the future revision.

Hope it helps. Again, thanks :)

**Comment by jimmy-dq** [comment]
> > Hi all, thanks for your great work. I am wondering that is the notation correct in table 1? since the original droptrack does not use the temporal information for tracking. Do you modify the original code to add the temporal information?
> 
> Hi jimmy-dq
> 
> Thank you very much for your comment. The notation for DropMAE should be DropTrack (DropMAE is the backbone, and we will correct this typo). In our evaluation, we don't modify the code of DropTrack. The reason why we add the 'temporal check' for DropTrack is because temporal relationship in the video has been explored and effectively utilized during pre-training of DropMAE which is the foundation of DropTrack (, and thus we think temporal information has been explored for tracking algorithms that are developed based DropMAE). But of course, we agree that original DropTrack itself does not explicitly exploit the temporal information. We may make appropriate changes or add explanations for DropTrack in the future revision.
> 
> Hope it helps. Again, thanks :)

Thanks, yes, I agree that no explicit temporal information is leveraged in DropTrack. Thanks again for your patient explanation, very nice work!
